#!/bin/sh

# initramfs hook script header
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions
configure_networking

CURL_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"

echo "Welcome to pnet initramfs client system."
echo "Test"

# open a shell
sh

exit 0
