#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac
. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

# Copy binary and dependencies
copy_exec /home/master/git/pnet/build/boot/pnetb /sbin
copy_exec /bin/ping /bin
copy_exec /bin/curl /bin

# copy certs
mkdir -p ${DESTDIR}/etc/ssl/certs
cp /etc/ssl/certs/ca-certificates.crt ${DESTDIR}/etc/ssl/certs

exit 0
