
# ProjectCGI
# Copyright 2025 Tony McCall

set(CGICC_FOUND TRUE)
set(CGICC_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../lib/cgicc/include)
set(CGICC_LINK_LIBRARIES ${CMAKE_CURRENT_SOURCE_DIR}/../lib/cgicc/lib/cgicc.lib)
set(CGICC_BINS ${CMAKE_CURRENT_SOURCE_DIR}/../lib/cgicc/bin)

add_library (CGICC SHARED IMPORTED)
set_property (TARGET CGICC PROPERTY IMPORTED_IMPLIB ${CGICG_LINK_LIBRARIES})

# ignore header warnings
set_property(TARGET CGICC APPEND PROPERTY INTERFACE_SYSTEM_INCLUDE_DIRECTORIES ${CGICC_INCLUDE_DIR})

